### PR TITLE
"add weighted knn" & "add kdtree to knn"

### PR DESCRIPTION
**Pull request by FrozenKP**
#### add weighted knn
when Weighted is true, it will use weighted knn when predict.
```go
cls := knn.NewKnnClassifier("euclidean", "kdtree", 2)
cls.Weighted = true
```
#### add kdtree to knn
add a new argument to knn.NewKnnClassifier()
When using "linear", it will check all data when predict. 
When using "kdtree", it will find k nearest points from kdtree. It's more efficient in some conditions.
```go
cls := knn.NewKnnClassifier("euclidean", "linear", 2)
cls := knn.NewKnnClassifier("euclidean", "kdtree", 2)
```

### CODE REVIEW

**Comment by Sentimentron** [comment]
Looks good, thanks for the contribution.

**Comment by FrozenKP** [comment]
Why closed？ Is there anything wrong？

**Comment by Sentimentron** [comment]
Oops, I think I pushed the wrong button.

**Comment by Sentimentron** [comment]
I'm sorry about that.

**Comment by FrozenKP** [comment]
That's OK. Thank you.

**Pull request merged**
