### PR TITLE
add Cosine distance for knn 

### PR DESCRIPTION
**Pull request by FrozenKP**
as title

### CODE REVIEW

**Comment by linkerlin** [comment]
Could you  use SSE/AVS?

**Comment by FrozenKP** [comment]
@linkerlin 
Can you give me more detailed information about "SSE/AVS"?

**Comment by linkerlin** [comment]
@FrozenKP 
Intel had added some SIMD instructions in their CPUs which can speed up MAD ops very much.

**Comment by linkerlin** [comment]
@FrozenKP 
Or you can use [OpenCL](https://github.com/Patagonicus/opencl) to speed up Matrix computing.
https://github.com/Patagonicus/opencl

**Pull request merged**
