### PR TITLE
Implementation of PCA

### PR DESCRIPTION
**Pull request by saromanov**
Hi, guys! I started to implement PCA and this is working version, but with mat64.Dense as parameter instand base.FixedDataGrid, because i not found nice way to take matrix of data from FixedDataGrid and apply it to mat64.SVD. 
This is simple usage

``` go
//Number of components
pca := NewPCA(2)
//X - some matrix
pca.Transform(X)
```

What do you think and should i continue to work on this task?

### CODE REVIEW

**Comment by Sentimentron** [comment]
Looks great, I've got to say. 

Don't worry too much about the FixedDataGrid thing.

**Comment by sjwhitworth** [comment]
Hey @saromanov. I'm going to have a look into this in the next few days - thanks for doing it.

**Comment by Sentimentron** [comment]
@sjwhitworth Should we merge this?

**Comment by grahamannett** [comment]
Hey, I have a bunch of thing's (functions and structs pulled basically from python libraries that don't need theano) I've been using with this library, is there a best practice to go about to pull request these (all at once or stepwise for understandability) as there is a bit of interdependence?

**Comment by nickpoorman** [comment]
+1

**Comment by njern** [comment]
@sjwhitworth this looks fine to me, what do you think, merge?

**Pull request merged**
