### PR TITLE
[kdtree] fixed a bug and change function name

### PR DESCRIPTION
**Pull request by FrozenKP**
- change searchAllNode to searchAllNodes

- find a bug when testing knn with kdtree (fixed)

### CODE REVIEW

**Comment by FrozenKP** [comment]
There are something wrong, don't merge !!

I am checking it.

**Comment by FrozenKP** [comment]
Find a bug of srcRowNo and fixed it. Everything work fine now.

**Comment by FrozenKP** [comment]
@Sentimentron @sjwhitworth 
Can you review this merge request? I have added kdtree to knn, but it can't pass test with origin kdtree.

Thank you.

**Comment by Sentimentron** [comment]
Let's see how this one goes.

**Pull request merged**
