### PR TITLE
add "zh_TW" and moving "zh" to "zh_CN"

### PR DESCRIPTION
**Pull request by FrozenKP**

### CODE REVIEW

**Comment by FrozenKP** [comment]
What's going on? I just add docs of Traditional Chinese......

**Comment by FrozenKP** [comment]
@Sentimentron
Can you help me figure out the problem? I think that's a bug of travis. BTW, someone told me that he faced the same problem when building gin-gonic/gin without changing anything. 

the problem is : every versions pass the test, while tip fail.

**Comment by Sentimentron** [comment]
I've restarted the build. If tip fails again, I don't think there will be a problem merging this, because it's not a code change.

**Comment by FrozenKP** [comment]
Thank a lot.

**Comment by FrozenKP** [comment]
@Sentimentron It seemed to fail again...

**Comment by Sentimentron** [comment]
OK, as a work-around, I've disabled testing against the latest go tip.

**Pull request merged**
